apiVersion: v2
name: distr
description: Ship self-hosted software
keywords:
  - distr
  - software distribution
  - on-prem management
  - docker
  - kubernetes
maintainers:
  - name: Distr Team
    email: support@distr.sh
    url: https://distr.sh
icon: >-
  https://github.com/distr-sh/distr/raw/refs/heads/main/frontend/ui/public/distr-logo.svg
home: https://distr.sh/docs/
type: application
version: 4.0.0
appVersion: 4.0.0
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.10.0
    condition: postgresql.enabled
  - name: rustfs
    repository: https://charts.rustfs.com
    version: 1.0.0-rc.5
    condition: rustfs.enabled
  - name: loki
    repository: oci://ghcr.io/grafana-community/helm-charts
    version: 18.12.1
    condition: loki.enabled
